Module5 task1
htmlacademy-react/767343-what-to-watch-6 pull request #7
Opened 2021-03-29 19:22 UTC by zhenya-mikhin

2021-03-30 09:21 UTC, IArny requested changes

2021-03-30 09:21 UTC, IArny commented on src/components/blocks/genres.jsx
> +              key={genre + i}
а зачем `+i`? достаточно genre, он же уникальный

2021-03-30 09:21 UTC, IArny commented on src/store/reducer.js
> +        films: getFilmByGenre(state.films, action.payload)
получатся, когда ты отфильтруешь 2ой раз у тебя ни одного фильма не найдет же, или все ок?

2021-03-30 09:21 UTC, IArny commented on src/components/blocks/genres.jsx
> +    dispatch(ActionCreator.getFiltredFilms(genre));
лучше фильтрацию не в сторе делать, а в самом компоненте или в селекторе (reselect)

2021-03-30 11:45 UTC, zhenya-mikhin commented on src/store/reducer.js
> +        films: getFilmByGenre(state.films, action.payload)
у меня сейчас фильтрация вообще не работает, не могу понять почему

2021-03-31 10:10 UTC, IArny commented on src/store/reselector.js
> +export const getFilmsByGenre = (genre, films) => {
По правильному будет передавать в селектор целеком весь state, и уже внутри него брать нужные тебе поля

2021-03-31 10:11 UTC, IArny requested changes

2021-03-31 10:11 UTC, IArny commented on src/components/pages/main/main.jsx
> +  films: getFilmsByGenre(state.activeGenre, state.films),
кажется тут ошибка
```suggestion
  films: getFilmsByGenre(state.genre, state.films),
```

2021-04-01 09:33 UTC, IArny approved these changes

2021-04-01 09:33 UTC, merged